### PR TITLE
Drop coffeescript, other fixes and improvements

### LINKED ISSUE #21: Set up Travis CI
Ideally, there should be some real tests for the project.

### LINKED ISSUE #39: Time to say bye to CoffeeScript
Need to convert coffee files to JS.

Decaffeinate output seems ok, but will require a small bit of tweaking.

https://github.com/decaffeinate/decaffeinate#readme

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @RayViljoen: if it's hard to review, try the non-whitespace diff with `?w=1`

Fixes #39, fixes #21 

TODO:

* [ ] Add Travis CI to the repo; we need an admin for this

### CODE REVIEW

**Comment by XhmikosR** [comment]
Ping @RayViljoen

**Comment by XhmikosR** [comment]
@RayViljoen: can you add the repo in Travis?

Also, how about npm publish rights? We should release a new version (major).

**Comment by RayViljoen** [comment]
@XhmikosR you should have publish on NPM. Same "write access" I have.
Also, I've sent you an invite to admin this repo.
Apologies for the long response times.

**Comment by XhmikosR** [comment]
@RayViljoen: thanks! Unfortunately I can't seem to be able to add Travis myself to the repo. Can you add it?

**Comment by RayViljoen** [comment]
I've added this repo to Travis. Changed a bit from when I last used it.. (some years)
Hopefully that works. Shout if not.

**Comment by XhmikosR** [comment]
All good now, I released a new version.

We really need tests :/

**Pull request merged**
